### ISSUE TITLE
Correct version of the dependencies

### ISSUE THREAD

**Issue by BEbillionaireUSD** [cedricrupb/code_graph#1]
Hi, I try to run the example but get an Error:
```
Traceback (most recent call last):
  File "/Users/cheryl/Desktop/a.py", line 3, in <module>
    cg.codegraph(
  File "/Users/cheryl/Desktop/code_graph/code_graph/__init__.py", line 65, in codegraph
    root_node, tokens = preprocess_code(source_code, lang, **kwargs)
  File "/Users/cheryl/Desktop/code_graph/code_graph/__init__.py", line 94, in preprocess_code
    return default_preprocess(source_code, lang, **kwargs)
  File "/Users/cheryl/Desktop/code_graph/code_graph/__init__.py", line 98, in default_preprocess
    tokens = ctok.tokenize(source_code, lang = lang, **kwargs)
  File "/Users/cheryl/miniconda/envs/py310/lib/python3.10/site-packages/code_tokenize/__init__.py", line 65, in tokenize
    parser = ASTParser(config.lang)
  File "/Users/cheryl/miniconda/envs/py310/lib/python3.10/site-packages/code_ast/parsers.py", line 88, in __init__
    self.lang    = load_language(lang)
  File "/Users/cheryl/miniconda/envs/py310/lib/python3.10/site-packages/code_ast/parsers.py", line 53, in load_language
    return Language(compiled_lang_path, lang)
TypeError: __init__() takes exactly 1 argument (2 given)
```
I think this is due to the update of tree-sitter, but I don't know which version I should choose to run this repo. Could you please provide a more detailed requirement list?

**Comment by cedricrupb** [comment]
Hey! Sorry for the delayed reply. If you update `code_ast` with `pip install --upgrade code_ast`, the problem should be resolved.
